name: C CI

on:
  push:
    branches: [ master ]
      tags:
        - 'v*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
      run: tar czf release.tar.gz umicat conf systemd docs LICENSE README.md

    - name: Release
      uses: actions/create-release@master
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release@master
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        assets_path: ./release.tar.gz
        asset_name: release-${{ github.ref }}.tar.gz